TERMINALS = {
    "TERMINATOR": 0,
    "IDENTIFIER": 0,
    "NUMBER": 0,
    "REGISTER": "register",
    "INSTRUCTION": "instruction",
    "BITS": 0,
    "LEFT_BRACKET": "{",
    "EQUAL": "=",
    "COLON": ":",
    "RIGHT_BRACKET": "}",
    "MACHINE": "machine",
    "IMMEDIATE": "immediate",
    "EVALUATION": 0,
    "MEMORY": "memory",
    "WIDTH": 0,
    "ITEM_KEY": 0,
    "SET": "set",
    "Pattern": 0,
    "COMMA": ",",
}
