/**
 * Project Name: machine
 * Module Name: codegen/C
 * Filename: static.c
 * Creator: Yaokai Liu
 * Create Date: 2024-12-11
 * Copyright (c) 2024 Yaokai Liu. All rights reserved.
 **/

#include "static.h"
#include <stdio.h>
#include <string.h>

constexpr char_t HEADER_FMT[] =
    "/**\n"
    " * Filename: %s\n"
    " *\n"
    " * This file is generated by xMachine, adopts the MIT License:\n"
    " *      MIT License\n"
    " *      Copyright (c) %d %s\n"
    " *\n"
    " *      Permission is hereby granted, free of charge, to any person obtaining a copy\n"
    " *      of this software and associated documentation files (the \"Software\"), to deal\n"
    " *      in the Software without restriction, including without limitation the rights\n"
    " *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
    " *      copies of the Software, and to permit persons to whom the Software is\n"
    " *      furnished to do so, subject to the following conditions:\n"
    " *\n"
    " *      The above copyright notice and this permission notice shall be included in all\n"
    " *      copies or substantial portions of the Software.\n"
    " *\n"
    " *      THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
    " *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
    " *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
    " *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
    " *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
    " *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
    " *      SOFTWARE.\n"
    " *\n"
    " * *The following appendix is not included in the License.*\n"
    " *\n"
    " * Appendix\n"
    " * ==================== xMachine =======================\n"
    " * xMachine - A Backend Generator for Compilers\n"
    " * xMachine adopts the GNU AFFERO GENERAL PUBLIC LICENSE.\n"
    " * Copyright (c) 2024 Yaokai Liu. All rights reserved.\n"
    " * =====================================================\n"
    " *\n"
    " **/";

constexpr char_t INCLUDES[] = "#include \"machine-%s.h\"\n"
                              "#include <stdarg.h>\n";

constexpr char_t EXPORT_INCLUDES[] = "#include <stdint.h>\n"
                                     "#include \"array.h\"\n";

constexpr char_t MACROS[] =
    "#define min(a, b)             ((a) < (b)) ? (a) : (b)\n"
    "#define UINT_N_MAX(n_bits)    (n_bits == 64 ? -1 : ((1LLU << (n_bits)) - 1))\n"
    "#define LOW_BITS(val, n_bits) ((val) & UINT_N_MAX(n_bits))\n"
    "#define MASK_BITS(bl, bu)     (UINT_N_MAX(bu) - UINT_N_MAX(bl))\n"
    "#define numSetBits(num, bl, bu, val) \\\n"
    "  (((num) & ~MASK_BITS(bl, bu)) | (LOW_BITS(val, (bu) - (bl)) << (bl)))\n"
    "#define setEncodingNumber(val) \\\n"
    "  do { number = (val); } while (false)\n"
    "#define pushInstrBytes(_count)                 \\\n"
    "  do {                                         \\\n"
    "    uint32_t last = min(_count + index, size); \\\n"
    "    for (uint32_t i = index; i < last; i++) {  \\\n"
    "      bytes[i] = number & 0xFF;                \\\n"
    "      number >>= 8;                            \\\n"
    "    }                                          \\\n"
    "    index = last;                              \\\n"
    "  } while (false)\n"
    "#define pushEncodingNumber(val, count) \\\n"
    "  do {                                 \\\n"
    "    setEncodingNumber(val);            \\\n"
    "    pushInstrBytes(count);             \\\n"
    "  } while (false)\n";

constexpr char_t EXPORT_DECLARE[] = "typedef struct Entry Entry;\n";

constexpr char_t TYPEDEF_ENTRY[] = "typedef struct Entry {\n"
                                   "  enum ENTRY_TYPE_ENUM type;\n"
                                   "  uint64_t value;\n"
                                   "} Entry;\n";

constexpr char_t TYPEDEF_MACHINE_FMT[] = "typedef struct {\n"
                                         "  uint32_t argCount;\n"
                                         "  Entry entries[%u];\n"
                                         "} Machine;\n";

constexpr char_t CURRENT_MACHINE[] = "Machine *CURRENT_MACHINE;\n";

constexpr char_t MAX_ARGS_DECLARE[] = "constexpr uint32_t MAX_ARGS;\n";
constexpr char_t MAX_ARGS_FMT[] = "constexpr uint32_t MAX_ARGS = %u;\n";

constexpr char_t STRUCT_JUMP_ITEM[] = "struct jump_item {\n"
                                      "  enum ENTRY_TYPE_ENUM expected_type;\n"
                                      "  uint32_t next_state_index;\n"
                                      "};\n";

constexpr char_t STRUCT_JUMP_STATE[] = "struct jump_state {\n"
                                       "  uint32_t count;\n"
                                       "  uint32_t index;\n"
                                       "  uint32_t (*fn_encoding)(Array *, uint64_t[]);\n"
                                       "};\n";

constexpr char_t STRUCT_SET_GRP_JUMP_STATE[] = "struct set_grp_jump_state {\n"
                                               "  uint32_t count;\n"
                                               "  uint32_t index;\n"
                                               "};\n";

constexpr char_t ENTRY_TYPE_CHECK_DEC[] =
    "bool entry_type_check(enum ENTRY_TYPE_ENUM type1, enum ENTRY_TYPE_ENUM type2);\n";
constexpr char_t ENTRY_TYPE_CHECK_DEF[] =
    "bool entry_type_check(enum ENTRY_TYPE_ENUM type1, enum ENTRY_TYPE_ENUM type2) {\n"
    "  if (type1 == type2) { return type1 < enum_BEGIN_SET_GRP; }\n"
    "  else if (enum_BEGIN_SET_GRP < type1 && type1 < enum_TYPE_ENUM_UPPER_BOUND) {\n"
    "    auto state = &SET_GRP_STATE_TABLE[type1 - enum_BEGIN_SET_GRP + 1];\n"
    "    for (uint32_t i = 0 ; i < state->count; i ++) {\n"
    "      type1 = SET_GRP_VAL_TABLE[state->index + i];\n"
    "      if (entry_type_check(type1, type2)) { return true; }\n"
    "    }\n"
    "  }\n"
    "  return false;\n"
    "}\n";

constexpr char_t CONVERT_INSTR_TO_BYTES_DEC[] =
    "uint32_t convert_instr_to_bytes(\n"
    "    uint32_t offset, Array *buffer, enum ENTRY_TYPE_ENUM types[],\n"
    "    uint64_t values[], uint32_t n_args\n"
    ");\n";
constexpr char_t CONVERT_INSTR_TO_BYTES_DEF[] =
    "uint32_t convert_instr_to_bytes(\n"
    "    uint32_t offset, Array *buffer, enum ENTRY_TYPE_ENUM types[],\n"
    "    uint64_t values[], uint32_t n_args\n"
    ") {\n"
    "  auto state = &JUMP_STATE_TABLE[offset];\n"
    "  uint32_t ndx = 0;\n"
    "  while (ndx < n_args) {\n"
    "    bool matched = false;\n"
    "    for (uint32_t j = 0; j < state->count; j++) {\n"
    "      auto type1 = &JUMP_KEY_TABLE[state->index + j];\n"
    "      if (entry_type_check(type1->expected_type, types[ndx])) {\n"
    "        matched = true;\n"
    "        offset = type1->next_state_index;\n"
    "        break;\n"
    "      }\n"
    "    }\n"
    "    if (!matched) { return 0; }\n"
    "    state = &JUMP_STATE_TABLE[offset];\n"
    "  }\n"
    "  if (!state->fn_encoding) { return 0; }\n"
    "  return state->fn_encoding(buffer, values);\n"
    "}\n";

constexpr char_t EXPORT_HEADER_FMT[] = "#ifndef MACHINE_%s_H\n"
                                       "#define MACHINE_%s_H\n\n";

constexpr char_t EXPORT_TAIL_FMT[] = "\n#endif  // MACHINE_%s_H\n";

void gen_header(
    GContext *context, Array *buffer, char_t *filename, int32_t year, char_t *cr_holder
) {
  uint32_t fn_len = strlen(filename);
  uint32_t cr_len = strlen(cr_holder);
  int32_t size = sizeof(HEADER_FMT) + fn_len + cr_len + 32;
  char_t *temp_buffer = context->allocator->malloc(size);
  sprintf(temp_buffer, HEADER_FMT, filename, year, cr_holder);
  Array_append(buffer, temp_buffer, size);
  context->allocator->free(temp_buffer);
}

#define ctx_push_string(type, s) \
  do { Array_append(Generator_getOutputBuffer(generator, CtxBuf_##type), s, strlen(s)); } while (false)

#define push_string(s) \
  do { Array_append(buffer, s, strlen(s)); } while (false)

void gen_static_definitions(Generator *generator, const Machine *machine) {
  char_t temp_buffer[256];
  sprintf(temp_buffer, INCLUDES, machine->name->ptr);
  ctx_push_string(includes, temp_buffer);
  ctx_push_string(macros, MACROS);
  ctx_push_string(types, TYPEDEF_ENTRY);
  sprintf(temp_buffer, TYPEDEF_MACHINE_FMT, machine->context->maxArgCount);
  ctx_push_string(types, temp_buffer);
  ctx_push_string(types, STRUCT_JUMP_ITEM);
  ctx_push_string(types, STRUCT_JUMP_STATE);
  ctx_push_string(types, STRUCT_SET_GRP_JUMP_STATE);
  ctx_push_string(declares, CURRENT_MACHINE);
  ctx_push_string(declares, MAX_ARGS_DECLARE);
  ctx_push_string(declares, ENTRY_TYPE_CHECK_DEC);
  ctx_push_string(declares, CONVERT_INSTR_TO_BYTES_DEC);
}
void gen_driver(Generator *generator, const Machine *machine) {
  char_t temp_buffer[256];
  sprintf(temp_buffer, MAX_ARGS_FMT, machine->context->maxArgCount);
  ctx_push_string(definitions, temp_buffer);
  ctx_push_string(definitions, ENTRY_TYPE_CHECK_DEF);
  ctx_push_string(definitions, CONVERT_INSTR_TO_BYTES_DEF);
}

void gen_export_header(Generator *generator, const Machine *machine) {
  char_t temp_buffer[256];
  const char_t * const name = machine->name->ptr;
  sprintf(temp_buffer, EXPORT_HEADER_FMT, name, name);
  ctx_push_string(exports, temp_buffer);
  ctx_push_string(exports, EXPORT_INCLUDES);
  ctx_push_string(exports, EXPORT_DECLARE);
}

void gen_export_tail(Generator *generator, const Machine *machine) {
  char_t temp_buffer[256];
  const char_t * const name = machine->name->ptr;
  sprintf(temp_buffer, EXPORT_TAIL_FMT, name);
  ctx_push_string(exports, temp_buffer);
}
