/* License
 *
 * xMachine - A Backend Generator for Compilers
 * Copyright (C) 2025 Yaokai Liu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 * Project Name: machine
 * Module Name: codegen
 * Filename: gen-export.c
 * Creator: Yaokai Liu
 * Create Date: 2025-02-20
 * Copyright (c) 2025 Yaokai Liu. All rights reserved.
 **/

#include "gen-export.h"
#include "declare-fmt.h"
#include "generator.h"
#include <stdio.h>
#include <string.h>

#define lenof(a)  (sizeof(a) / sizeof(a[0]))
#define ctx_ident_real(ptr) Array_virt2real(ident_array, ptr)

constexpr char_t EXPORT_HEADER_FMT[] = "#ifndef MACHINE_%s_H\n"
                                       "#define MACHINE_%s_H\n\n";

constexpr char_t LICENSE_FMT[] =
    "/**\n"
    " * Filename: %s\n"
    " *\n"
    " * This file is generated by xMachine, adopts the MIT License:\n"
    " *      MIT License\n"
    " *      Copyright (c) %s %s\n"
    " *\n"
    " *      Permission is hereby granted, free of charge, to any person obtaining a copy\n"
    " *      of this software and associated documentation files (the \"Software\"), to deal\n"
    " *      in the Software without restriction, including without limitation the rights\n"
    " *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
    " *      copies of the Software, and to permit persons to whom the Software is\n"
    " *      furnished to do so, subject to the following conditions:\n"
    " *\n"
    " *      The above copyright notice and this permission notice shall be included in all\n"
    " *      copies or substantial portions of the Software.\n"
    " *\n"
    " *      THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
    " *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
    " *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
    " *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
    " *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
    " *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
    " *      SOFTWARE.\n"
    " *\n"
    " * *The following appendix is not included in the License.*\n"
    " *\n"
    " * Appendix\n"
    " * ==================== xMachine =======================\n"
    " * xMachine - A Backend Generator for Compilers\n"
    " * xMachine adopts the GNU AFFERO GENERAL PUBLIC LICENSE.\n"
    " * Copyright (c) 2024 Yaokai Liu. All rights reserved.\n"
    " * =====================================================\n"
    " *\n"
    " **/\n\n";

constexpr char_t EXPORT_INCLUDES[] = "#include <stdint.h>\n"
                                     "#include \"array.h\"\n";

constexpr char_t EXPORT_DECLARE_FMT[] = "typedef struct %sMachine %sMachine;\n"
                                        "typedef struct Entry Entry;\n";

constexpr char_t MACHINE_NEW_DEC_FMT[] = "%sMachine *%sMachine_new(const Allocator *allocator);\n";
constexpr char_t MACHINE_DESTROY_DEC_FMT[] = "void %sMachine_destroy(%sMachine *machine);\n";
const char_t* MACHINE_FUNCTION_FMTS[] = {
    "void useMachine(%sMachine *machine);\n",
    "int32_t activateReg(%sMachine *machine, const Entry *reg_entry);\n",
    "int32_t inactivateReg(%sMachine *machine, const Entry *reg_entry);\n",
    "int32_t dumpActiveRegs(%sMachine *machine, void * const *dest);\n",
    "int32_t loadActiveRegs(%sMachine *machine, void *_from);\n",
};
constexpr char_t ENCODING_INSTR_DEC[] =
    "// Notice: arguments of this function must end with an EOI.\n"
    "uint32_t encodingInstr(Array *buffer, uint32_t instr, ...);\n";

constexpr char_t INSTR_ENUM_HEAD[] = "enum INSTR_ENUM : uint32_t {\n";
constexpr char_t INSTR_ENUM_ITEM_FNT[] = "  INSTR_%s = %d,\n";
constexpr char_t INSTR_ENUM_TAIL[] = "};\n";

constexpr char_t EXPORT_TAIL_FMT[] = "enum MACHINE_ERROR_TYPE {\n"
                                     "  ERR_SUCCESS = 0,\n"
                                     "  ERR_TYPE_MISMATCH = 1,\n"
                                     "  ERR_ARGUMENT_MISSING = 2,\n"
                                     "  ERR_FORM_CHECK_FAULT = 3,\n"
                                     "};\n"
                                     "#endif  // MACHINE_%s_H\n";

#define ctx_push_string(type, s)                                                                   \
  do {                                                                                             \
    Array_append(CGenerator_getOutputBuffer((CGenerator *) generator, GenC_##type), s, strlen(s)); \
  } while (false)

#define push_string(s) \
  do { Array_append(buffer, s, strlen(s)); } while (false)

void gen_license(Generator *generator, Array *buffer, const char_t *filename) {
  if (!generator->year || !generator->cr_holder) {
    printf("no year or cr_holder.\n");
    return;
  }
  const char_t *year = generator->year;
  const char_t *cr_holder = generator->cr_holder;
  char_t temp_buffer[2048] = {};
  sprintf(temp_buffer, LICENSE_FMT, filename, year, cr_holder);
  push_string(temp_buffer);
}

void gen_export_header(Generator *generator, const Machine *machine) {
  char_t temp_buffer[256];
  Array * const out_buffer = CGenerator_getOutputBuffer((CGenerator *) generator, GenC_exports);
  const char_t * const name = Array_virt2real(generator->ident_array, machine->name);
  const char_t *filename;
  if (generator->headpath) {
    filename = strrchr(generator->headpath, '/');
    filename = filename ? filename + 1 : generator->headpath;
  } else {
    filename = "";
  }
  gen_license(generator, out_buffer, filename);
  sprintf(temp_buffer, EXPORT_HEADER_FMT, name, name);
  ctx_push_string(exports, temp_buffer);
  ctx_push_string(exports, EXPORT_INCLUDES);
  sprintf(temp_buffer, EXPORT_DECLARE_FMT, name, name);
  ctx_push_string(exports, temp_buffer);
  sprintf(temp_buffer, MACHINE_NEW_DEC_FMT, name, name);
  ctx_push_string(exports, temp_buffer);
  sprintf(temp_buffer, MACHINE_DESTROY_DEC_FMT, name, name);
  ctx_push_string(exports, temp_buffer);
  for (uint32_t i = 0; i < lenof(MACHINE_FUNCTION_FMTS); i++) {
    sprintf(temp_buffer, MACHINE_FUNCTION_FMTS[i], name);
    ctx_push_string(exports, temp_buffer);
  }
  ctx_push_string(exports, ENCODING_INSTR_DEC);
  const ParseContext *context = machine->context;
  const Array *ident_array = generator->ident_array;
  const uint32_t n_instr = Array_length(context->instrArray);
  const Instruction *instructions = Array_real_addr(context->instrArray, 0);
  ctx_push_string(exports, INSTR_ENUM_HEAD);
  for (uint32_t i = 0; i < n_instr; i++) {
    sprintf(
        temp_buffer, INSTR_ENUM_ITEM_FNT, ctx_ident_real(instructions[i].name),
        instructions[i].entry_offset
    );
    ctx_push_string(exports, temp_buffer);
  }
  ctx_push_string(exports, INSTR_ENUM_TAIL);
}
const char_t IF_USING_INSTR_DIRECTLY[] = "\n#ifdef USING_INSTR_DIRECTLY\n";
const char_t END_IF[] = "#endif\n";
const char_t INSTR_EXEC_DEC[] =
    "#define %s(...)  encodingInstr(PROG_INSTR_BUFFER, INSTR_%s, __VA_ARGS__, EOI)\n";
void gen_export_instr_macro(Generator *generator, const Machine *machine) {
  char_t temp_buffer[512] = {};
  const ParseContext *context = machine->context;
  const Array *ident_array = generator->ident_array;
  const uint32_t n_instr = Array_length(context->instrArray);
  const Instruction *instructions = Array_real_addr(context->instrArray, 0);
  ctx_push_string(exports, IF_USING_INSTR_DIRECTLY);
  for (uint32_t i = 0; i < n_instr; i++) {
    const char_t *instr_name = ctx_ident_real(instructions[i].name);
    sprintf(temp_buffer, INSTR_EXEC_DEC, instr_name, instr_name);
    ctx_push_string(exports, temp_buffer);
  }
  ctx_push_string(exports, END_IF);
}

void gen_export_tail(Generator *generator, const Machine *machine) {
  char_t temp_buffer[256];
  const char_t * const name = Array_virt2real(generator->ident_array, machine->name);
  sprintf(temp_buffer, EXPORT_TAIL_FMT, name);
  ctx_push_string(exports, temp_buffer);
}

void gen_mem_dec(const ParseContext *context, const Array *ident_array, Array *buffer);
void gen_mem_dec_sprintf(
    const Memory *mem, const ParseContext *context, const Array *ident_array, char_t *temp_buffer,
    Array *buffer
);
#define gen_record_sprintf(Type, var, ...)                         \
  do {                                                             \
    const uint32_t count = Array_length(context->var##Array);      \
    const Type *entries = Array_real_addr(context->var##Array, 0); \
    for (uint32_t i = 0; i < count; i++) {                         \
      sprintf(temp_buffer, __VA_ARGS__);                           \
      push_string(temp_buffer);                                    \
    }                                                              \
  } while (false)

#define gen_imm_sprintf(...) gen_record_sprintf(Immediate, imm, __VA_ARGS__)
#define gen_reg_sprintf(...) gen_record_sprintf(Register, reg, __VA_ARGS__)
void gen_export_record_declare(Generator *generator, const Machine *machine) {
  char_t temp_buffer[512] = {};
  const ParseContext *context = machine->context;
  const Array *ident_array = generator->ident_array;
  Array *buffer = CGenerator_getOutputBuffer((CGenerator *) generator, GenC_exports);
  push_string("extern const Entry *const EOI;\n");
  gen_mem_dec(context, ident_array, buffer);
  gen_imm_sprintf(IMM_DEC_FMT, ctx_ident_real(entries[i].name));
  gen_reg_sprintf(REG_DEC_FMT, ctx_ident_real(entries[i].name));
}

inline void gen_mem_dec_sprintf(
    const Memory *mem, const ParseContext *context, const Array *ident_array, char_t *temp_buffer,
    Array *buffer
) {
  sprintf(temp_buffer, MEM_DEC_NAME_FMT, ctx_ident_real(mem->name));
  push_string(temp_buffer);
  push_string("(");
  const uint32_t n_items = Array_length(mem->items);
  const MemItem *items = Array_real_addr(mem->items, 0);
  for (uint32_t i = 0; i < n_items; i++) {
    const Identifier *ident = ctx_ident_real(items[i].name);
    if (items[i].type) {
      const Record *record = GContext_findRecord(context, items[i].type);
      if (record->typeid == enum_Immediate) {
        sprintf(temp_buffer, "uint64_t *%s", ident);
      } else {
        sprintf(temp_buffer, "const Entry *%s", ident);
      }
    } else {
      sprintf(temp_buffer, "uint64_t %s", ident);
    }
    push_string(temp_buffer);
    if (i < n_items - 1) {
      push_string(", ");
    } else {
      push_string(")");
    }
  }
}

void gen_mem_dec(const ParseContext *context, const Array *ident_array, Array *buffer) {
  char_t temp_buffer[512] = {};
  const uint32_t count = Array_length(context->memArray);
  const Memory *memories = Array_real_addr(context->memArray, 0);
  for (uint32_t i = 0; i < count; i++) {
    const Memory *mem = &memories[i];
    gen_mem_dec_sprintf(mem, context, ident_array, temp_buffer, buffer);
    push_string(";\n");
  }
}
