/* License
 *
 * xMachine - A Backend Generator for Compilers
 * Copyright (C) 2025 Yaokai Liu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 * Project Name: machine
 * Module Name: codegen
 * Filename: gen-export.c
 * Creator: Yaokai Liu
 * Create Date: 2025-02-20
 * Copyright (c) 2025 Yaokai Liu. All rights reserved.
 **/

#include "gen-export.h"
#include "declare-fmt.h"
#include "generator.h"
#include <stdio.h>
#include <string.h>

#define lenof(a)            (sizeof(a) / sizeof(a[0]))
#define ctx_ident_real(ptr) Array_virt2real(ident_array, ptr)

constexpr char_t EXPORT_HEADER_FMT[] = "#ifndef MACHINE_%s_H\n"
                                       "#define MACHINE_%s_H\n\n";

constexpr char_t LICENSE_FMT[] =
    "/**\n"
    " * Filename: %s\n"
    " *\n"
    " * This file is generated by xMachine, adopts the MIT License:\n"
    " *      MIT License\n"
    " *      Copyright (c) %s %s\n"
    " *\n"
    " *      Permission is hereby granted, free of charge, to any person obtaining a copy\n"
    " *      of this software and associated documentation files (the \"Software\"), to deal\n"
    " *      in the Software without restriction, including without limitation the rights\n"
    " *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
    " *      copies of the Software, and to permit persons to whom the Software is\n"
    " *      furnished to do so, subject to the following conditions:\n"
    " *\n"
    " *      The above copyright notice and this permission notice shall be included in all\n"
    " *      copies or substantial portions of the Software.\n"
    " *\n"
    " *      THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
    " *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
    " *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
    " *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
    " *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
    " *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
    " *      SOFTWARE.\n"
    " *\n"
    " * *The following appendix is not included in the License.*\n"
    " *\n"
    " * Appendix\n"
    " * ==================== xMachine =======================\n"
    " * xMachine - A Backend Generator for Compilers\n"
    " * xMachine adopts the GNU AFFERO GENERAL PUBLIC LICENSE.\n"
    " * Copyright (c) 2024 Yaokai Liu. All rights reserved.\n"
    " * =====================================================\n"
    " *\n"
    " **/\n\n";

constexpr char_t EXPORT_INCLUDES[] = "#include <stdint.h>\n"
                                     "#include \"array.h\"\n";

constexpr char_t EXPORT_DECLARE_FMT[] = "typedef struct %sMachine %sMachine;\n"
                                        "typedef struct Entry Entry;\n";

constexpr char_t MACHINE_NEW_DEC_FMT[] = "%sMachine *%sMachine_new(const Allocator *allocator);\n";
constexpr char_t MACHINE_DESTROY_DEC_FMT[] = "void %sMachine_destroy(%sMachine *machine);\n";
const char_t *MACHINE_FUNCTION_FMTS[] = {
    "void useMachine(%sMachine *machine);\n",
    "int32_t activateReg(%sMachine *machine, const Entry *reg_entry);\n",
    "int32_t inactivateReg(%sMachine *machine, const Entry *reg_entry);\n",
    "int32_t dumpActiveRegs(%sMachine *machine, void * const *dest);\n",
    "int32_t loadActiveRegs(%sMachine *machine, void *_from);\n",
};
constexpr char_t ENCODING_INSTR_DEC[] =
    "// Notice: arguments of this function must end with an EOI.\n"
    "uint32_t encodingInstr(Array *buffer, uint32_t instr, ...);\n";

constexpr char_t INSTR_ENUM_HEAD[] = "enum INSTR_ENUM : uint32_t {\n";
constexpr char_t INSTR_ENUM_ITEM_FNT[] = "  INSTR_%s = %d,\n";
constexpr char_t INSTR_ENUM_TAIL[] = "};\n";

constexpr char_t EXPORT_TAIL_FMT[] = "enum MACHINE_ERROR_TYPE {\n"
                                     "  ERR_SUCCESS = 0,\n"
                                     "  ERR_TYPE_MISMATCH = 1,\n"
                                     "  ERR_ARGUMENT_MISSING = 2,\n"
                                     "  ERR_FORM_CHECK_FAULT = 3,\n"
                                     "};\n"
                                     "#endif  // MACHINE_%s_H\n";

void gen_license(
    const char_t *cr_holder, const char_t *year, const char_t *filename, FILE *ostream
) {
  if (!year || !cr_holder) {
    printf("no year or cr_holder.\n");
    return;
  }
  fprintf(ostream, LICENSE_FMT, filename, year, cr_holder);
}

void gen_export_header(const Generator *generator, const Machine *machine) {

  const char_t *filename;
  if (generator->headpath) {
    filename = strrchr(generator->headpath, '/');
    filename = filename ? filename + 1 : generator->headpath;
  } else {
    filename = "";
  }
  gen_license(generator->cr_holder, generator->year, filename, generator->ostream_head);

  const char_t * const machine_name = Array_virt2real(generator->ident_array, machine->name);
  fprintf(generator->ostream_head, EXPORT_HEADER_FMT, machine_name, machine_name);
  fputs(EXPORT_INCLUDES, generator->ostream_head);
  fprintf(generator->ostream_head, EXPORT_DECLARE_FMT, machine_name, machine_name);
  fprintf(generator->ostream_head, MACHINE_NEW_DEC_FMT, machine_name, machine_name);
  fprintf(generator->ostream_head, MACHINE_DESTROY_DEC_FMT, machine_name, machine_name);
  for (uint32_t i = 0; i < lenof(MACHINE_FUNCTION_FMTS); i++) {
    fprintf(generator->ostream_head, MACHINE_FUNCTION_FMTS[i], machine_name);
  }
  fputs(ENCODING_INSTR_DEC, generator->ostream_head);
  const ParseContext *context = machine->context;
  const Array *ident_array = generator->ident_array;
  const uint32_t n_instr = Array_length(context->instrArray);
  const Instruction *instructions = Array_real_addr(context->instrArray, 0);
  fputs(INSTR_ENUM_HEAD, generator->ostream_head);
  for (uint32_t i = 0; i < n_instr; i++) {
    fprintf(
        generator->ostream_head, INSTR_ENUM_ITEM_FNT, ctx_ident_real(instructions[i].name),
        instructions[i].entry_offset
    );
  }
  fputs(INSTR_ENUM_TAIL, generator->ostream_head);
}

constexpr char_t IF_USING_INSTR_DIRECTLY[] = "\n#ifdef USING_INSTR_DIRECTLY\n";
constexpr char_t END_IF[] = "#endif\n";
constexpr char_t INSTR_EXEC_DEC[] =
    "#define %s(...)  encodingInstr(PROG_INSTR_BUFFER, INSTR_%s, __VA_ARGS__, EOI)\n";
void gen_export_instr_macro(const Generator *generator, const Machine *machine) {
  const ParseContext *context = machine->context;
  const Array *ident_array = generator->ident_array;
  const uint32_t n_instr = Array_length(context->instrArray);
  const Instruction *instructions = Array_real_addr(context->instrArray, 0);
  fputs(IF_USING_INSTR_DIRECTLY, generator->ostream_head);
  for (uint32_t i = 0; i < n_instr; i++) {
    const char_t *instr_name = ctx_ident_real(instructions[i].name);
    fprintf(generator->ostream_head, INSTR_EXEC_DEC, instr_name, instr_name);
  }
  fputs(END_IF, generator->ostream_head);
}

void gen_export_tail(const Generator *generator, const Machine *machine) {
  const char_t * const name = Array_virt2real(generator->ident_array, machine->name);
  fprintf(generator->ostream_head, EXPORT_TAIL_FMT, name);
}

void gen_mem_dec(Generator *generator, const ParseContext *context, const Array *ident_array);
void gen_mem_dec_fprintf(
    FILE *ostream, const Memory *mem, const ParseContext *context, const Array *ident_array
);
#define gen_record_fprintf(ostream, Type, var, ...)                \
  do {                                                             \
    const uint32_t count = Array_length(context->var##Array);      \
    const Type *entries = Array_real_addr(context->var##Array, 0); \
    for (uint32_t i = 0; i < count; i++) {                         \
      fprintf(ostream, __VA_ARGS__);                               \
    }                                                              \
  } while (false)

#define gen_imm_sprintf(ostream, ...) gen_record_fprintf(ostream, Immediate, imm, __VA_ARGS__)
#define gen_reg_sprintf(ostream, ...) gen_record_fprintf(ostream, Register, reg, __VA_ARGS__)
void gen_export_record_declare(Generator *generator, const Machine *machine) {
  const ParseContext *context = machine->context;
  const Array *ident_array = generator->ident_array;
  fputs("extern const Entry *const EOI;\n", generator->ostream_head);
  gen_mem_dec(generator, context, ident_array);
  gen_imm_sprintf(generator->ostream_head, IMM_DEC_FMT, ctx_ident_real(entries[i].name));
  gen_reg_sprintf(generator->ostream_head, REG_DEC_FMT, ctx_ident_real(entries[i].name));
}

inline void gen_mem_dec_fprintf(
    FILE *ostream, const Memory *mem, const ParseContext *context, const Array *ident_array
) {
  fprintf(ostream, MEM_DEC_NAME_FMT, ctx_ident_real(mem->name));
  fputs("(", ostream);
  const uint32_t n_items = Array_length(mem->items);
  const MemItem *items = Array_real_addr(mem->items, 0);
  for (uint32_t i = 0; i < n_items; i++) {
    const Identifier *ident = ctx_ident_real(items[i].name);
    if (items[i].type) {
      const Record *record = GContext_findRecord(context, items[i].type);
      if (record->typeid == Machine_TOKEN_Immediate) {
        fprintf(ostream, "uint64_t *%s", ident);
      } else {
        fprintf(ostream, "const Entry *%s", ident);
      }
    } else {
      fprintf(ostream, "uint64_t %s", ident);
    }
    fputs((i < n_items - 1) ? ", " : ")", ostream);
  }
}

void gen_mem_dec(Generator *generator, const ParseContext *context, const Array *ident_array) {
  const uint32_t count = Array_length(context->memArray);
  const Memory *memories = Array_real_addr(context->memArray, 0);
  for (uint32_t i = 0; i < count; i++) {
    const Memory *mem = &memories[i];
    gen_mem_dec_fprintf(generator->ostream_head, mem, context, ident_array);
    fputs(";\n", generator->ostream_head);
  }
}
