TERMINALS = {
        "INSTRUCTION": "instruction",
        "REG_KEY": 0,
        "IMMEDIATE": "immediate",
        "COMMA": ",",
        "COLON": ":",
        "MACHINE": "machine",
        "SEMICOLON": ";",
        "TIME_TICK": 0,
        "BIT_FIELD": 0,
        "MEM_KEY": 0,
        "PATTERN": 0,
        "SET": "set",
        "EVALUATABLE": 0,
        "PART_KEY": 0,
        "WIDTH": 0,
        "LEFT_BRACKET": "{",
        "NUMBER": 0,
        "IDENTIFIER": 0,
        "MEMORY": "memory",
        "TYPE": "unsigned",
        "RIGHT_BRACKET": "}",
        "EQUAL": "=",
        "REGISTER": "register",
        "TERMINATOR": 0,
}
